baseURL = "/"
title = "Big Movies"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "Big Movies" # title for frontpage, may include image
copyright = "bigmovie.in"
description = 'Entertainment for your Soul <br /><br />screened by <a href="https://bigmovie.in">BIG Movies, </a><br /><br />Showcased to You,<a href="https://bigmovie.in"></a> by Cine Artists.'
startbuttonText = "Enjoy"
startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/films/'
title = "Film Collections"

[[params.menu.main]]
url = '/reviews/'
title = "reviews"

[[params.menu.main]]
url = '/cnews/'
title = "news"

[[params.menu.main]]
url = '/interviews/'
title = "Interviews"

[[params.menu.main]]
url = '/awards/'
title = "awards"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Top 10 Indian Movies<br />Reviews by You, Experts and Artists'
body = '''
We all like to see a film and review it, as an independent person. We are delightful to present our own thoughts and feelings of the film, we have just seen, to our friends and all..
'''

[[params.one.icon]]
icon = "fa-pencil-square-o"
style = "3"
label = "Dolor"
url = "https://google.com"

[[params.one.icon]]
icon = "fa-heart-o"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "fa-diamond"
style = "1"
label = "Lorem"

[params.two]
enable = true

[[params.two.section]]
img = "img/pic01.jpg"
title = 'Vikram<br /> Multilingual movie'
body = 'A classic Kamal movie, a story about crusade against drug peddlars.'

[[params.two.section]]
img = "img/pic02.jpg"
title = 'Tortor dolore feugiat<br />elementum magna'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[[params.two.section]]
img = "img/pic03.jpg"
title = 'Magna primis lobortis<br />sed ullamcorper'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[params.three]
enable = true
title = 'Accumsan mus tortor nunc aliquet'
body = '''
Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend  
fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
'''

[[params.three.feature]]
icon = "fa-paper-plane-o"
title = "Arcu accumsan"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-laptop"
title = "Ac Augue Eget"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-code"
title = "Foo bar"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-headphones"
title = "Baz kram"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-heart-o"
title = "Some latin text"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-flag-o"
title = "Nothing important"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[params.cta]
enable = true
title = "Arcue ut vel commodo"
body = "Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla."

[[params.cta.link]]
href = "#"
text = "Activate"
special = true

[[params.cta.link]]
href = "#"
text = "See More"
special = false

[params.contact]
enable = true
title = "Contact"
body = "Leave us a message."
phone = "+91 9445 415 843"
address = "Chennai,<br />Tamil Nadu, <br />India 603103"
email = "murruganpn@gmail.com"
subject = "New Submission!"
plain = false

[params.social]
twitter = ""
facebook = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"
