baseURL = "/"
title = "Big Movies"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "Big Movies" # title for frontpage, may include image
copyright = "bigmovie.in"
description = 'Entertainment for your Soul <br /><br /><a href="https://bigmovie.in">BIG Movies</a> - We create, You Applaud<br /><br />Showcased to You,<a href="https://bigmovie.in"></a> by Cine Artists.'
startbuttonText = "Enjoy"
startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/films/'
title = "Film Collections"

[[params.menu.main]]
url = '/reviews/'
title = "reviews"

[[params.menu.main]]
url = '/cnews/'
title = "news"

[[params.menu.main]]
url = '/interviews/'
title = "Interviews"

[[params.menu.main]]
url = '/awards/'
title = "awards"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Top 10 Indian Movies<br />Reviews by You, Experts and Artists'
body = '''
We all like to see a film and review it, as an independent person. We are delightful to present our own thoughts and feelings of the film, we have just seen, to our friends and all..
'''

[[params.one.icon]]
icon = "fa-pencil-square-o"
style = "3"
label = "Dolor"
url = "https://google.com"

[[params.one.icon]]
icon = "fa-heart-o"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "fa-diamond"
style = "1"
label = "Lorem"

[params.two]
enable = true

[[params.two.section]]
img = "img/vikram.jpg"
title = 'Vikram<br /> Multilingual movie'
body = 'A classic Kamal movie, a story about crusade against drug peddlars.'

[[params.two.section]]
img = "img/film.jpg"
title = 'Motion Pictures<br />Production Management'
body = 'Producing, Managing and Distribution of films.'

[[params.two.section]]
img = "img/sonyliv.jpg"
title = 'OTT - Over the Top<br />Streaming of films'
body = 'SonyLiv Aggregator.'

[params.three]
enable = true
title = 'Think Script Action Release'
body = '''
Produce Film Content Better, Smarter, Together..
'''

[[params.three.feature]]
icon = "fa-paper-plane-o"
title = "Producer"
body = "We help you to find and launch a film; arrange the film's finance; hire screenwriters, a director, and key members of the creative team; and oversee all elements of pre-production, production, and post-production, right up to the film's release."

[[params.three.feature]]
icon = "fa-laptop"
title = "Aggregator"
body = "We as a company help to distribute your film and visual content to streaming platforms like SonyLiv, Netflix, Disney Hotstar, Amazon, Jio and MX player."

[[params.three.feature]]
icon = "fa-code"
title = "Financing"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-headphones"
title = "Digital Marketing"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-heart-o"
title = "Creative Arts & Design"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-flag-o"
title = "Television Media"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[params.cta]
enable = true
title = "Arcue ut vel commodo"
body = "Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla."

[[params.cta.link]]
href = "#"
text = "Activate"
special = true

[[params.cta.link]]
href = "#"
text = "See More"
special = false

[params.contact]
enable = true
title = "Contact"
body = "Leave us a message."
phone = "+91 9597 777 789"
address = "Chennai,<br />Tamil Nadu, <br />India 600115"
email = "murruganpn1@bigmovie.in"
subject = "New Submission!"
plain = false

[params.social]
twitter = ""
facebook = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"
